project:
  name: 'delivery'
template_vars:
  - key: STACK
    value: delivery

canary_configs:
  - name: 'broker'
    templateName: 'something'

pipelines:
  - name: bake
    templateName: bake.json
  - name: deploy-to-devint
    templateName: devint.json
    regions:
      - name: us-east4
        account: ox-delivery-devint-24-us-east4
  - name: deploy-to-qa
    templateName: qa.json
    regions:
      # TODO: multi-region QA is not yet supported due to downstream trigger issues
      # - name: us-west1
      #   outputName: qa-us-west1-42.json
      #   account: ox-delivery-qa-42-us-west1
      #   template_vars:
      #     - key: INSTANCE_NUMBER
      #       value: 42
      - name: us-east4
        # outputName: qa-us-west1-24.json
        account: ox-delivery-qa-24-us-east4
    # allow yardfile-wide trigger config?
    notifications:
      - type: slack
        address: ci-cd-notifications
  - name: deploy-to-prod
    templateName: prod.json
    regions:
      # live production traffic
      - name: asia-northeast1
        account: ox-delivery-prod-1-asia-northeast1
      - name: asia-southeast1
        account: ox-delivery-prod-1-asia-southeast1
      - name: europe-west1
        account: ox-delivery-prod-42-europe-west1
      - name: us-central1
        account: ox-delivery-prod-42-us-central1
      - name: us-east1
        account: ox-delivery-prod-42-us-east1
      # doesn't exist
      # - name: us-east4
      #   account: ox-delivery-prod-42-us-east4
      - name: us-west1
        account: ox-delivery-prod-42-us-west1
      # doesn't exist
      # - name: us-west2
      #   account: ox-delivery-prod-42-us-west2
      # new VPC
      # issues spinning up k8s in region
      # - name: asia-northeast1
      #   account: ox-delivery-prod-42-asia-northeast1
      - name: asia-southeast1
        account: ox-delivery-prod-42-asia-southeast1
      - name: europe-west1
        account: ox-delivery-prod-42-europe-west1
      - name: us-central1
        account: ox-delivery-prod-42-us-central1
      # live production traffiic
      - name: us-east1
        account: ox-delivery-prod-42-us-east1
      - name: us-east4
        account: ox-delivery-prod-42-us-east4
      - name: us-west1
        account: ox-delivery-prod-42-us-west1
      - name: us-west2
        account: ox-delivery-prod-42-us-west2
    notifications:
      - type: slack
        address: ci-cd-notifications

apps:
  ads:
    pipelines:
      - name: deploy-to-devint
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: ads-managed
          pipeline: bake
      - name: deploy-to-qa
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: ads-managed
          pipeline: deploy-to-devint
          region: us-east4
      - name: deploy-to-prod
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: ads-managed
          pipeline: deploy-to-qa
          # TODO: make regions + pipeline pairs easier to manage
          region: us-east4
    # TODO: move to overrides
    template_vars:
      - key: IMAGE_TAG_PATH
        value: dsAdvertiser.image.tag

  currencyservice:
    pipelines:
      - name: deploy-to-devint
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: ads-managed
          pipeline: bake
      - name: deploy-to-qa
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: currencyservice-managed
          pipeline: deploy-to-devint
          region: us-east4
      - name: deploy-to-prod
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: currencyservice-managed
          pipeline: deploy-to-qa
          # TODO: make regions + pipeline pairs easier to manage
          region: us-east4
    # TODO: move to overrides
    template_vars:
      - key: IMAGE_TAG_PATH
        value: deployment.containers.currencyservice.imageTag

  weightwatchers:
    pipelines:
      - name: bake
        templateName: bake.json
      - name: deploy-to-devint
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: weightwatchers-managed
          pipeline: bake
      - name: deploy-to-qa
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: weightwatchers-managed
          pipeline: deploy-to-devint
          region: us-east4
      - name: deploy-to-prod
        triggers:
        - type: pipeline
          # TODO: drop managed when it's not hard coded to the uploader
          application: weightwatchers-managed
          pipeline: deploy-to-qa
          # TODO: make regions + pipeline pairs easier to manage
          region: us-east4
    # TODO: move to overrides
    template_vars:
      - key: IMAGE_TAG_PATH
        value: deployment.containers.weightwatchers.imageTag
